# Pull base image. We reference a pre-built image available on DockerHub
FROM tomcat:9.0.82-jdk8-corretto

# Maintainer for this Image 
MAINTAINER "nus-iss-grp1" 

# Copy to war file to tomcat path  
ADD target/user.war /usr/local/tomcat/webapps/user.war
